version: "3"
services:
    mySQL_curso:
    hostname: meu-mysql
    image: mysql
    restart: always
    command:
        - --default-authentication-plugin=mysql_native_password
        - --character-set-server=utf8mb4
        - --collation-server=utf8mb4_unicode_ci
        - --innodb_force_recovery=0
      volumes: 
        - ~/mySQL_curso:/var/lib/mysql
      ports:
        - 3306:3306
      environment:
        MYSQL_ROOT_PASSWORD: root
        MYSQL_DATABASE: base_de_dados
        MYSQL_USER: usuario
        MYSQL_PASSWORD: rooto
        TZ: America/Sao_Paulo